version: "3.9"

services:

  traefik:
    image: traefik:v3.6
    command:
      - "--providers.docker=true"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.websecure.address=:443"

      # ACME
      - "--certificatesresolvers.myresolver.acme.httpchallenge=true"
      - "--certificatesresolvers.myresolver.acme.httpchallenge.entrypoint=web"
      - "--certificatesresolvers.myresolver.acme.email=adrian.wojewoda@gmail.com"
      - "--certificatesresolvers.myresolver.acme.storage=/acme.json"

      # Metrics
      - "--entrypoints.metrics.address=:8082"
      - "--metrics.prometheus=true"
      - "--metrics.prometheus.entrypoint=metrics"

      - "--log.level=INFO"
      - "--accesslog=true"

    ports:
      - "80:80"
      - "443:443"

    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./acme.json:/acme.json

    restart: unless-stopped

  prometheus:
    image: prom/prometheus:v2.52.0
    volumes:
      - ./monitoring/prometheus.yml:/etc/prometheus/prometheus.yml:ro
      
    restart: unless-stopped

  grafana:
    image: grafana/grafana:11.1.0
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=haselkomaselko
      - GF_USERS_ALLOW_SIGN_UP=false
    volumes:
      - ./monitoring/grafana/provisioning:/etc/grafana/provisioning:ro
      - ./monitoring/grafana/dashboards:/var/lib/grafana/dashboards:ro
    labels:
      - "traefik.enable=true"

      # HTTP -> HTTPS
      - "traefik.http.routers.grafana.rule=Host(`grafana.adiwoj.pl`)"
      - "traefik.http.routers.grafana.entrypoints=web"
      - "traefik.http.routers.grafana.middlewares=redirect-to-https"

      # HTTPS
      - "traefik.http.routers.grafana-secure.rule=Host(`grafana.adiwoj.pl`)"
      - "traefik.http.routers.grafana-secure.entrypoints=websecure"
      - "traefik.http.routers.grafana-secure.tls=true"
      - "traefik.http.routers.grafana-secure.tls.certresolver=myresolver"
      - "traefik.http.services.grafana.loadbalancer.server.port=3000"

    restart: unless-stopped

  database:
     image: postgres:16
     environment:
       POSTGRES_DB: erp
       POSTGRES_USER: postgres
       POSTGRES_PASSWORD: postgres
     volumes:
       - postgres_data:/var/lib/postgresql/data
     restart: unless-stopped

  backend:
    build: ../../../app/backend
    environment:
      DATABASE_URL: postgresql://postgres:postgres@db:5432/erp
    depends_on:
      - db
    labels:
       - "traefik.enable=true"
       - "traefik.http.routers.erp.rule=Host(`erp.adiwoj.pl`)"
       - "traefik.http.routers.erp.entrypoints=websecure"
       - "traefik.http.routers.erp.tls=true"
       - "traefik.http.routers.erp.tls.certresolver=myresolver"
       - "traefik.http.services.erp.loadbalancer.server.port=8000"
    restart: unless-stopped

  volumes:
     postgres_data: